name: Bug report
description: Report a problem in code, docs, or CI
labels: ["bug"]
body:
  - type: textarea
    id: desc
    attributes:
      label: What happened?
      description: Clear, minimal reproduction if possible.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Commands, files, or links
  - type: input
    id: lean
    attributes:
      label: Lean version (`lean --version`)
  - type: input
    id: lake
    attributes:
      label: Lake version (`lake --version`)
